FROM gcc
ARG NAME="ctf"
ENV CTF_NAME=$NAME
RUN mkdir /home/$CTF_NAME
RUN mkdir /home/$CTF_NAME/src
COPY ./ctfs/$CTF_NAME/makefile /home/$CTF_NAME/makefile
COPY ./ctfs/$CTF_NAME/src/$CTF_NAME.cpp /home/$CTF_NAME/src/$CTF_NAME.cpp
WORKDIR /home/$CTF_NAME
RUN make build_linux_x86
RUN mv /home/$CTF_NAME/bin/${CTF_NAME}_x86_elf /home/ctf
RUN rm -rf /home/$CTF_NAME/
CMD /home/ctf
