FROM gcc
ARG NAME="ctf"
ENV CTF_NAME=$NAME
RUN mkdir /home/$CTF_NAME
COPY ./ctfs/$CTF_NAME/makefile /home/$CTF_NAME/makefile
COPY ./ctfs/$CTF_NAME/$CTF_NAME.cpp /home/$CTF_NAME/$CTF_NAME.cpp
COPY ../../helpers/char2byte_offset/char2byte_offset.hpp /home/$CTF_NAME/char2byte_offset.hpp
COPY ../../helpers/get_input.hpp /home/$CTF_NAME/get_input.hpp
WORKDIR /home/$CTF_NAME
RUN make build_linux_x86
RUN mv /home/$CTF_NAME/bin/${CTF_NAME}_x86_elf /home/ctf
RUN rm -rf /home/$CTF_NAME/
CMD /home/ctf
