FROM gcc
ARG NAME="ctf"
ENV CTF_NAME=$NAME
RUN mkdir /home/build
COPY ./$CTF_NAME/makefile /home/build/makefile
COPY ./$CTF_NAME/client0.cpp /home/build/client0.cpp
COPY ./$CTF_NAME/server0.cpp /home/build/server0.cpp
COPY ./$CTF_NAME/socket_header.hpp /home/build/socket_header.hpp
COPY ./$CTF_NAME/launch_bg.sh /home/launch_bg.sh
WORKDIR /home/build
RUN make build_linux_x86
RUN mv /home/build/bin/server0_x86_elf /home/server
RUN mv /home/build/bin/client0_x86_elf /home/client
RUN rm -rf /home/build/
CMD /home/launch_bg.sh
